logging:
  level.org.springframework: INFO
  level.com.dbg: DEBUG
spring:
  datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/doctors
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect